name: Publish Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: redkubes/docusaurus-deploy-action@v1.1
        with:
          source-folder: "."
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GH_TOKEN }}
          deployment-branch: gh-pages
